<a href="https://colab.research.google.com/github/santhoshipola/datas2/blob/master/Day_10(04_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
###Nine lives:
import random
lives = 9
heart_symbol = '\u2764'
words = ["hello","pizza","apple","mouse","light"]
secret_word = random.choice(words)
clue = list('?????')
guessed_word_correctly = False


In [0]:
def update_clue(guessed_letter,secret_word,clue):
  index = 0
  while index < len(secret_word):
    if guessed_letter == secret_word[index]:
      clue[index] = guessed_letter
    index += 1


In [11]:
while lives>0:
  print(clue)
  print("lives left:",heart_symbol*lives)
  guess = input("Enter a letter or whole word :")
  if guess == secret_word:
    guessed_word_correctly = True
    break
  elif guess in secret_word:
    update_clue(guess,secret_word,clue)
  else:
    print("Incorrect guess!!You lost a life")
    lives -= 1
if guessed_word_correctly == True:
  print("you guessed the word correctly!Secret_word is:",secret_word)
else:
  print("your guess is wrong.Secret_word is:",secret_word)


['a', 'p', 'p', 'l', 'e']
lives left: ❤❤❤❤❤❤
Enter a letter or whole word :apple
you guessed the word correctly!Secret_word is: apple


#**NUMPY PACKAGE**

In [0]:
-NUmerical Data
-computations and numerics



In [0]:
import numpy as np##Ususally np is considered as alias word

In [0]:
#Differences between numpy array and List:previous session

In [14]:
# 1-dimensional array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(a1.ndim)#gives dimension

2


In [17]:
a1.shape#for num of rows and columns

(3, 3)

In [18]:
a.shape

(5,)

In [21]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape)
print(a2.shape[0])#rows
print(a2.shape[1])#columns

(4, 3)
4
3


In [0]:
a3 = np.array([1,2,3,4,5])#1d and 2d array
a4 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [0]:
#inserting elements into the array dynamically
a5 = np.array([])# or np.array([],dtype = "int32") to make the given input as integer


In [28]:
a5 = np.append(a5,int(input()))#a5 at first is necessary 
print(a5)
a5.dtype


15
[12. 12. 15.]


dtype('float64')

In [30]:
a3 = np.append(a3,[23,34,56,67,89])
a3

array([ 1,  2,  3,  4,  5, 23, 34, 56, 67, 89, 23, 34, 56, 67, 89])

In [31]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
##Slicing:

In [33]:
print(a5[2])

15.0


In [34]:
print(a2[1,1])

5


In [35]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [36]:
print(a2[2:,0:2])#0,1 columns are considered

[[ 7  8]
 [10 11]]


In [37]:
print(a2[0,0:2])

[1 2]


In [0]:
###Iterate through array:

In [41]:
for row in a2:
  print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [42]:
list1 = [1,2,3,4]
for i in list1:
  print(i)

1
2
3
4


In [43]:
list1 = [[1,2],[3,4]]
for i in list1:
  print(i)

[1, 2]
[3, 4]


In [44]:
for ele in a2.flat:#a2.flat gives all elements regardless of shape
  print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [45]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
#Indexing with Boolean arrays

In [48]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [52]:
result = (arr1 % 2 == 0)#to extract even numbers
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [53]:
arr1 [result]#boolean to normal array to get even numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
#Appending arrays

In [58]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))#vertical stacking           it accepts only one argument   so tuple is given


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [59]:
print(np.hstack((arr1,arr2)))#horizontal stacking                          in both sizes of arrays must be matched

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [0]:
#Attributes:
-size
-itemsize
-dtype
-ndim
-shape

In [60]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
8
int64
2
(2, 5)


In [0]:
#Functions:
-zeros
-ones
-full
-eye
-linspace
arange
reshape
ravel

In [65]:
z = np.zeros((2,3),dtype ="int32")#in output dtype should not come here
z

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [68]:
o = np.ones((3,3),dtype="int32")
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [67]:
f = np.full((2,2),"santu")
print(f)

[['santu' 'santu']
 ['santu' 'santu']]


In [71]:
#eye
e = np.eye(3,dtype="int32")
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [73]:
#linspace()-->linear spacing elements are returned
l = np.linspace(1,10,5)
print(l)

[ 1.    3.25  5.5   7.75 10.  ]


In [76]:
a = np.arange(1,13,2)#range(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [77]:
a.shape

(6,)

In [79]:
a = a.reshape(2,3)#to reshape
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [82]:
#ravel():-->flattens your array elements
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


In [0]:
#Function:
min()
max()
sum()
sqrt()
mean()
median()#numpy donot have mode function
std()

In [84]:
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [85]:
print(a.min())
print(a.max())

1
11


In [86]:
print(a.sum())##sum of all elements of the arrrray

36


In [88]:
print(a.sum(axis=1))#sum of row elements
print(a.sum(axis=0))#sum of column elements

[ 9 27]
[ 8 12 16]


In [89]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [90]:
np.mean(a)

6.0

In [91]:
np.median(a)

6.0

In [92]:
np.std(a)##standard deviation

3.415650255319866

In [0]:
#######Mathematical operations:
+,-,*,/,%

In [96]:
a6 = np.arange(1,11) 
a7 = np.arange(11,21)
print(a6 + a7)
print(a6 - a7)
print(a6 * a7)
print(a6 / a7)
print(a6 % a7)


[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


In [0]:
#dot()-->Matrix multiplication
#arr1 = m x n
#arr2 = n x l

In [97]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [98]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
arr1.T#transpose of an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [0]:
#Applying user defined functions:

In [100]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [103]:
a = np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [0]:
x/(x+1)-->1/(1+1)

In [102]:
result =  [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [104]:
f = np.vectorize(lambda x:x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [0]:
help(np.linalg)

In [0]:
help(np.random)